import java.io.*;
import java.nio.file.*;
import org.microemu.app.Headless;
import org.microemu.MIDletBridge;
import javax.microedition.midlet.MIDlet;
import javax.microedition.lcdui.Display;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Element;
public final class HeadlessSmoke {
    public static void main(String[] args) throws Exception {
        try { run(args); } catch (Throwable e) { e.printStackTrace(); System.exit(1); }
    }
    static void run(String[] args) throws Exception {
        File game = new File(args[0]), home = new File(args[1]);
        home.mkdirs(); File status = new File(home, "bridge.status");
        AccountBootstrap.verifyContract(game);
        AccountBootstrap.prepare(home, game, "fixture-user", " fixture-pass ", 2);
        System.setProperty("user.home", home.getAbsolutePath());
        System.setProperty("java.awt.headless", "true");
        Headless.main(new String[] { "--rms", "file", "--openjar", game.getAbsolutePath() });
        AccountBootstrap.loginWhenReady("fixture-user", " fixture-pass ", 2, status);
        String value = new String(Files.readAllBytes(status.toPath()), "UTF-8");
        if (!value.equals("LOGIN_SUBMITTED")) { System.err.println("FAIL: headless emulator integration: " + value); System.exit(1); }
        System.out.println("PASS: real emulator starts fixture and submits correct account/password/server on its event thread (offline).");
        MIDlet midlet = MIDletBridge.getCurrentMIDlet();
        final ClassLoader loader = midlet.getClass().getClassLoader();
        File statistics = new File(home, "statistics-settings.xml");
        Files.write(statistics.toPath(), "<Settings><ShowUnder8>true</ShowUnder8><ShowTrackedItems>true</ShowTrackedItems><TrackedItemIds>123,456,999</TrackedItemIds></Settings>".getBytes("UTF-8"));
        final GameAccountObserver observer = new GameAccountObserver(status, true, statistics);
        tick(midlet, observer, loader);
        Class<?> selector = Class.forName("SelectCharScr", false, loader);
        if (selector.getField("selections").getInt(null) != 1) throw new AssertionError("First slot not automatically chosen.");
        tick(midlet, observer, loader);
        File info = new File(home, "character.xml");
        Element snapshot = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(info).getDocumentElement();
        if (!snapshot.getAttribute("name").equals("first-character") || !snapshot.getAttribute("xu").equals("3456") || !snapshot.getAttribute("luong").equals("78")) throw new AssertionError("Wrong character currency snapshot.");
        if (!snapshot.getAttribute("weaponState").equals("EQUIPPED") || !snapshot.getAttribute("weaponLevel").equals("50") || !snapshot.getAttribute("weaponUpgrade").equals("12")) throw new AssertionError("Equipped weapon info is missing.");
        if (!snapshot.getAttribute("boxKnown").equals("false") || snapshot.hasAttribute("boxXu")) throw new AssertionError("Unloaded chest must not be shown as zero.");
        String firstLogin = snapshot.getAttribute("loginUtc");
        if (firstLogin.isEmpty()) throw new AssertionError("Successful entry must include login time.");
        long unchangedTime = info.lastModified();
        Class<?> templates = Class.forName("ItemTemplates", false, loader);
        int lookups = templates.getField("knownLookups").getInt(null);
        tick(midlet, observer, loader);
        if (info.lastModified() != unchangedTime) throw new AssertionError("Identical character data must not rewrite the snapshot on every tick.");
        if (lookups != templates.getField("knownLookups").getInt(null)) throw new AssertionError("Known item names must use cache instead of repeated template lookups.");
        Element inventory = (Element)snapshot.getElementsByTagName("Inventory").item(0);
        if (!inventory.getAttribute("boxKnown").equals("false") || !((Element)inventory.getElementsByTagName("Item").item(0)).getAttribute("quantity").equals("2")) throw new AssertionError("Bag stacks must sum with chest marked unknown.");
        if (!((Element)inventory.getElementsByTagName("Item").item(1)).getAttribute("name").equals("Absent item") || !((Element)inventory.getElementsByTagName("Item").item(2)).getAttribute("name").equals("ID 999")) throw new AssertionError("Names must map from templates, with unknown-ID fallback.");
        Class<?> characterType = Class.forName("Char", false, loader);
        Object character = characterType.getMethod("getMyChar").invoke(null);
        characterType.getField("arrItemBox").set(character, new Object[0]);
        characterType.getField("xuInBox").setInt(character, 99);
        tick(midlet, observer, loader);
        snapshot = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(info).getDocumentElement();
        if (!snapshot.getAttribute("boxKnown").equals("true") || !snapshot.getAttribute("boxXu").equals("99")) throw new AssertionError("Server chest response not reflected.");
        characterType.getField("xu").setInt(character, 0);
        tick(midlet, observer, loader);
        snapshot = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(info).getDocumentElement();
        if (!snapshot.getAttribute("xu").equals("0")) throw new AssertionError("Loaded zero balance must stay valid.");
        Object[] equipment = (Object[])characterType.getField("arrItemBody").get(character);
        Object weapon = equipment[1], template = weapon.getClass().getField("template").get(weapon);
        weapon.getClass().getField("quantity").setInt(weapon, 3);
        characterType.getField("arrItemBox").set(character, new Object[] { weapon });
        tick(midlet, observer, loader);
        snapshot = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(info).getDocumentElement();
        inventory = (Element)snapshot.getElementsByTagName("Inventory").item(0);
        if (!((Element)inventory.getElementsByTagName("Item").item(0)).getAttribute("quantity").equals("5")) throw new AssertionError("Bag and chest quantities must be added once, excluding equipped items.");
        template.getClass().getField("isUpToUp").setBoolean(template, false);
        tick(midlet, observer, loader);
        snapshot = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(info).getDocumentElement();
        inventory = (Element)snapshot.getElementsByTagName("Inventory").item(0);
        if (!((Element)inventory.getElementsByTagName("Item").item(0)).getAttribute("quantity").equals("3")) throw new AssertionError("Non-stackable chest item counts as one, not its raw quantity.");
        template.getClass().getField("isUpToUp").setBoolean(template, true);
        weapon.getClass().getField("upgrade").setInt(weapon, 7);
        tick(midlet, observer, loader);
        snapshot = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(info).getDocumentElement();
        if (!((Element)snapshot.getElementsByTagName("Equipment").item(0)).getElementsByTagName("Item").item(0).getAttributes().getNamedItem("upgrade").getNodeValue().equals("7")) throw new AssertionError("Equipped +7 must appear below +8.");
        template.getClass().getField("type").setByte(template, (byte)10);
        tick(midlet, observer, loader);
        snapshot = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(info).getDocumentElement();
        if (((Element)snapshot.getElementsByTagName("Equipment").item(0)).getElementsByTagName("Item").getLength() != 0) throw new AssertionError("Non-upgradable body accessory must be excluded.");
        template.getClass().getField("type").setByte(template, (byte)1);
        weapon.getClass().getField("upgrade").setInt(weapon, 8);
        tick(midlet, observer, loader);
        snapshot = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(info).getDocumentElement();
        if (((Element)snapshot.getElementsByTagName("Equipment").item(0)).getElementsByTagName("Item").getLength() != 0) throw new AssertionError("Equipped +8 must be excluded.");
        weapon.getClass().getField("upgrade").setInt(weapon, 12);
        template.getClass().getField("level").setByte(template, (byte)130);
        tick(midlet, observer, loader);
        snapshot = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(info).getDocumentElement();
        if (!snapshot.getAttribute("weaponLevel").equals("130")) throw new AssertionError("Weapon level byte must be read unsigned.");
        equipment[1] = null;
        tick(midlet, observer, loader);
        snapshot = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(info).getDocumentElement();
        if (!snapshot.getAttribute("weaponState").equals("NONE") || snapshot.hasAttribute("weaponLevel")) throw new AssertionError("Empty weapon slot must not show old equipment.");
        characterType.getField("arrItemBody").set(character, null);
        tick(midlet, observer, loader);
        snapshot = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(info).getDocumentElement();
        if (!snapshot.getAttribute("weaponState").equals("UNKNOWN")) throw new AssertionError("Unloaded equipment must remain unknown.");
        if (Class.forName("Service", false, loader).getField("requests").getInt(null) != 1) throw new AssertionError("Must not flood server with chest requests.");
        Files.write(statistics.toPath(), "<Settings><ShowUnder8>false</ShowUnder8><ShowTrackedItems>false</ShowTrackedItems></Settings>".getBytes("UTF-8"));
        tick(midlet, observer, loader);
        snapshot = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(info).getDocumentElement();
        if (snapshot.getElementsByTagName("Inventory").getLength() != 0 || snapshot.getElementsByTagName("Equipment").getLength() != 0) throw new AssertionError("Statistics settings must refresh without restarting game.");
        System.out.println("PASS: item template names, bag/chest totals, under-eight equipment and live statistics switches (offline).");
        Object emptySelector = selector.newInstance();
        selector.getField("name").set(emptySelector, new String[] { null, "second-character", null });
        Class.forName("GameCanvas", false, loader).getField("currentScreen").set(null, emptySelector);
        tick(midlet, observer, loader);
        if (selector.getField("selections").getInt(null) != 1) throw new AssertionError("Empty first slot must not select or create another character.");
        if (!new String(Files.readAllBytes(status.toPath()), "UTF-8").equals("CHARACTER_SLOT_EMPTY")) throw new AssertionError("Empty first slot must be reported.");
        selector.getField("name").set(emptySelector, new String[] { "first-character", null, null });
        tick(midlet, observer, loader); tick(midlet, observer, loader);
        snapshot = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(info).getDocumentElement();
        String secondLogin = snapshot.getAttribute("loginUtc");
        if (secondLogin.isEmpty() || secondLogin.equals(firstLogin)) throw new AssertionError("Successful re-login in the same process must refresh login time.");
        Class<?> gameCanvas = Class.forName("GameCanvas", false, loader);
        gameCanvas.getField("isLoading").setBoolean(null, true); tick(midlet, observer, loader);
        gameCanvas.getField("isLoading").setBoolean(null, false); tick(midlet, observer, loader);
        snapshot = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(info).getDocumentElement();
        if (!snapshot.getAttribute("loginUtc").equals(secondLogin)) throw new AssertionError("Ordinary map loading must not count as another login.");
        System.out.println("PASS: slot one selected once, character and balances read, delayed chest stays unknown, response updates, empty slot does not create a character.");
        Files.deleteIfExists(new File(home, "auto-command.xml").toPath());
        Files.deleteIfExists(new File(home, "auto-result.xml").toPath());
        tick(midlet, observer, loader);
        Element autoState = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(new File(home, "auto-state.xml")).getDocumentElement();
        if (autoState.getElementsByTagName("Option").getLength() != 32) throw new AssertionError("Auto observer must expose all 32 visible game options.");
        if (!((Element)autoState.getElementsByTagName("Option").item(0)).getAttribute("value").equals("50")) throw new AssertionError("Auto observer must read numeric thresholds.");
        File autoCommand = new File(home, "auto-command.xml");
        Files.write(autoCommand.toPath(), "<AutoCommand session='fixture-session' id='1'><Set key='isAFood' enabled='true'/><Set key='ek' value='60'/></AutoCommand>".getBytes("UTF-8"));
        tick(midlet, observer, loader);
        if (!Class.forName("Char", false, loader).getField("isAFood").getBoolean(null) || Class.forName("Char", false, loader).getField("ek").getInt(null) != 60 || Class.forName("Char", false, loader).getField("isABuff").getBoolean(null)) throw new AssertionError("Partial Auto command must update only touched game fields.");
        if (!new String(Files.readAllBytes(new File(home, "auto-saved.txt").toPath()), "UTF-8").startsWith("true:60:")) throw new AssertionError("Auto changes must call the game's save method.");
        Element result = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(new File(home, "auto-result.xml")).getDocumentElement();
        if (!result.getAttribute("state").equals("OK") || !result.getAttribute("id").equals("1")) throw new AssertionError("Auto result must acknowledge the correct command.");
        int saves = Class.forName("Char", false, loader).getField("saves").getInt(null);
        tick(midlet, observer, loader);
        if (Class.forName("Char", false, loader).getField("saves").getInt(null) != saves) throw new AssertionError("Repeated Auto tick must not apply the same request again.");
        Files.write(autoCommand.toPath(), "<AutoCommand session='stale-session' id='2'><Set key='ek' value='70'/></AutoCommand>".getBytes("UTF-8"));
        tick(midlet, observer, loader);
        if (Class.forName("Char", false, loader).getField("ek").getInt(null) != 60) throw new AssertionError("Old session command must not affect a restarted game.");
        Files.write(autoCommand.toPath(), "<AutoCommand session='fixture-session' id='2'><Set key='ek' value='200'/></AutoCommand>".getBytes("UTF-8"));
        tick(midlet, observer, loader);
        result = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(new File(home, "auto-result.xml")).getDocumentElement();
        if (!result.getAttribute("state").equals("ERROR") || Class.forName("Char", false, loader).getField("ek").getInt(null) != 60) throw new AssertionError("Invalid threshold must report error without partial Auto mutation.");
        Files.write(autoCommand.toPath(), "<AutoCommand session='fixture-session' id='3'><Set key='weaponOnlyPickup' enabled='true'/></AutoCommand>".getBytes("UTF-8"));
        tick(midlet, observer, loader);
        if (!Class.forName("AutoDailyPanel", false, loader).getField("weaponOnlyPickup").getBoolean(null) || Class.forName("AutoDailyPanel", false, loader).getField("saves").getInt(null) != 1) throw new AssertionError("Weapon-only Auto mode must use the game's own save action.");
        Class.forName("Char", false, loader).getField("failSave").setBoolean(null, true);
        Files.write(autoCommand.toPath(), "<AutoCommand session='fixture-session' id='4'><Set key='ek' value='70'/></AutoCommand>".getBytes("UTF-8"));
        tick(midlet, observer, loader);
        result = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(new File(home, "auto-result.xml")).getDocumentElement();
        if (!result.getAttribute("state").equals("ERROR") || Class.forName("Char", false, loader).getField("ek").getInt(null) != 60) throw new AssertionError("Silent RMS save failure must not be reported as applied Auto.");
        Class.forName("Char", false, loader).getField("failSave").setBoolean(null, false);
        Class.forName("AutoDailyPanel", false, loader).getField("weaponOnlyPickup").setBoolean(null, false);
        Class.forName("mResources", false, loader).getField("autoDailyFlags").setInt(null, -1);
        Files.write(autoCommand.toPath(), "<AutoCommand session='fixture-session' id='5'><Set key='weaponOnlyPickup' enabled='false'/></AutoCommand>".getBytes("UTF-8"));
        tick(midlet, observer, loader);
        result = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(new File(home, "auto-result.xml")).getDocumentElement();
        if (!result.getAttribute("state").equals("OK")) throw new AssertionError("Unset AutoDaily RMS defaults to disabled, and confirming disabled should succeed.");
        Files.write(autoCommand.toPath(), "<AutoCommand session='fixture-session' id='6'><Set key='missingGameField' enabled='true'/></AutoCommand>".getBytes("UTF-8"));
        tick(midlet, observer, loader);
        result = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(new File(home, "auto-result.xml")).getDocumentElement();
        if (!result.getAttribute("state").equals("ERROR") || Class.forName("Char", false, loader).getField("ek").getInt(null) != 60) throw new AssertionError("Unsupported Auto field must reject only that command.");
        Files.write(autoCommand.toPath(), "<AutoCommand session='fixture-session' id='7'><Set key='ek' value='70'".getBytes("UTF-8"));
        tick(midlet, observer, loader);
        if (Class.forName("Char", false, loader).getField("ek").getInt(null) != 60 || !new File(home, "character.xml").isFile()) throw new AssertionError("Malformed Auto XML must not stop account observation.");
        Files.write(autoCommand.toPath(), new byte[65537]);
        tick(midlet, observer, loader);
        if (Class.forName("Char", false, loader).getField("ek").getInt(null) != 60 || !new File(home, "character.xml").isFile()) throw new AssertionError("Oversized Auto command must not affect game or account observation.");
        File unsupportedHome = new File(home, "unsupported-game"); unsupportedHome.mkdirs();
        new GameAutoController(unsupportedHome, "unsupported-session").tick(new ClassLoader(null) {});
        Element unsupported = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(new File(unsupportedHome, "auto-state.xml")).getDocumentElement();
        if (!unsupported.getAttribute("state").equals("UNSUPPORTED")) throw new AssertionError("Game versions without Auto fields must report unsupported state.");
        Object gameScreen = gameCanvas.getField("currentScreen").get(null);
        gameCanvas.getField("currentScreen").set(null, Class.forName("LoginScr", false, loader).newInstance());
        tick(midlet, observer, loader);
        autoState = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(new File(home, "auto-state.xml")).getDocumentElement();
        if (!autoState.getAttribute("state").equals("WAITING") || autoState.getElementsByTagName("Option").getLength() != 0) throw new AssertionError("Auto availability must clear when a tab leaves the game screen.");
        gameCanvas.getField("currentScreen").set(null, gameScreen);
        tick(midlet, observer, loader);
        autoState = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(new File(home, "auto-state.xml")).getDocumentElement();
        if (!autoState.getAttribute("state").equals("READY")) throw new AssertionError("Auto availability must recover after returning to game.");
        File resultPath = new File(home, "auto-result.xml");
        Files.delete(resultPath.toPath());
        if (!resultPath.mkdir()) throw new AssertionError("Could not create temporary blocked result path.");
        File blockingChild = new File(resultPath, "block"); Files.write(blockingChild.toPath(), new byte[] { 1 });
        Files.write(autoCommand.toPath(), "<AutoCommand session='fixture-session' id='8'><Set key='ek' value='70'/></AutoCommand>".getBytes("UTF-8"));
        tick(midlet, observer, loader);
        if (Class.forName("Char", false, loader).getField("ek").getInt(null) != 70) throw new AssertionError("Auto should apply even if the result file is temporarily blocked.");
        saves = Class.forName("Char", false, loader).getField("saves").getInt(null);
        Files.delete(blockingChild.toPath()); Files.delete(resultPath.toPath());
        tick(midlet, observer, loader);
        result = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(resultPath).getDocumentElement();
        if (!result.getAttribute("state").equals("OK") || !result.getAttribute("id").equals("8") || Class.forName("Char", false, loader).getField("saves").getInt(null) != saves) throw new AssertionError("Auto must retry a blocked acknowledgment without reapplying the command.");
        System.out.println("PASS: Auto observer exposes all game settings, applies partial changes once, persists, rejects stale/invalid requests (offline).");
        System.exit(0);
    }
    static void tick(MIDlet midlet, final GameAccountObserver observer, final ClassLoader loader) throws Exception {
        final java.util.concurrent.CountDownLatch done = new java.util.concurrent.CountDownLatch(1);
        final java.util.concurrent.atomic.AtomicReference<Throwable> error = new java.util.concurrent.atomic.AtomicReference<Throwable>();
        Display.getDisplay(midlet).callSerially(new Runnable() { public void run() {
            try { MIDletBridge.setThreadMIDletContext(MIDletBridge.getMIDletContext(MIDletBridge.getCurrentMIDlet())); observer.tick(loader); }
            catch (Throwable e) { error.set(e); } finally { done.countDown(); }
        } });
        if (!done.await(5, java.util.concurrent.TimeUnit.SECONDS)) throw new AssertionError("Game event thread did not run.");
        if (error.get() != null) throw new AssertionError(error.get());
    }
}
